services:
  scraper:  
    build:
      context: ./scraper
      dockerfile: Dockerfile
    volumes:
      - ./scraper:/app
    depends_on:
      - redis
      - mongo
      - elasticsearch
    env_file:
      - scraper/.env
    command: npm run dev rappler -- --elapse=360
  llm:
    build:
      context: ./llm
      dockerfile: Dockerfile
    volumes:
      - ./llm:/app
    env_file:
      - llm/.env
    ports:
      - 8000:8000
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - data:/data      
  redis:
    image: redis
    volumes:
      - redis:/data
    ports:
      - 6379:6379
  elasticsearch:
    image: elasticsearch:7.17.20
    environment:
      - discovery.type=single-node
    volumes:
      - es:/data
    ports:
      - 9200:9200
volumes:
  data:
  redis:
  es:
